### PR TITLE
Morph Phone class to Date class

### PR DESCRIPTION
**Pull request by hotarumin**

### CODE REVIEW

**Comment by CrimsonAng** [comment]
Looks alright, the checks passed.

**Comment by park-sang-jun** [comment]
You might want to change auto-format settings so that the individual imports do not get lumped together into a wild import.

**Comment by hotarumin** [comment]
How can I change the auto format settings?

**Comment by CrimsonAng** [comment]
> How can I change the auto format settings?

from https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.adoc

Go to File > Settings…​ (Windows/Linux), or IntelliJ IDEA > Preferences…​ (macOS)

Select Editor > Code Style > Java

Click on the Imports tab to set the order

For Class count to use import with '*' and Names count to use static import with '*': Set to 999 to prevent IntelliJ from contracting the import statements

For Import Layout: The order is import static all other imports, import java.*, import javax.*, import org.*, import com.*, import all other imports. Add a <blank line> between each import

**Comment by CrimsonAng** [comment]
I learnt that the hard way when renaming the project...keep fail travis and need 1by1 re-add everything

**Pull request merged**
